auth0:
  audience: https://quickstarts/api
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://squad-2.auth0.com/

spring.datasource.url=jdbc:h2:mem: testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.h2.console.enabled: true
